In [1]:
import pandas as pd
import plotly.express as px

In [2]:
from google.colab import drive
drive.mount('/content/drive')

ruta = "/content/drive/MyDrive/Colab Notebooks/IA/Mburicao/"

df0 = pd.read_csv(ruta + "Mburicao_Sil.csv",
                  header=None,
                  names=["fecha","nivel"])

Mounted at /content/drive

In [3]:
inicio = '2026-01-31 23:00:00' ##se adelanta 1 hora luego
fin = '2026-02-28 22:55:00'
mascara = (df0['fecha'] >= inicio) & (df0['fecha'] <= fin)
df_febrero = df0.loc[mascara].copy()

In [4]:
df_febrero['fecha'] = pd.to_datetime(df_febrero['fecha'])
df_febrero = df_febrero.sort_values('fecha').reset_index(drop=True)

In [5]:
def round_up_to_next_minute(ts):
    if ts.second != 0 or ts.microsecond != 0:
        # Suma los segundos restantes para llegar al minuto siguiente
        return ts + pd.Timedelta(seconds=(60 - ts.second), microseconds=-ts.microsecond)
    return ts

df_febrero['fecha'] = df_febrero['fecha'].apply(round_up_to_next_minute)

In [6]:
# Contar ocurrencias de cada fecha
conteo = df_febrero['fecha'].value_counts()

# Filtrar aquellas que aparecen más de una vez
repetidas = conteo[conteo > 1]

print(f"Total de fechas con repeticiones: {len(repetidas)}")
print("\nFechas repetidas y su frecuencia:")
print(repetidas)

# Opcional: mostrar las filas correspondientes a esas fechas para inspeccionar
if not repetidas.empty:
    # Crear una lista de las fechas repetidas
    fechas_repetidas = repetidas.index.tolist()
    # Filtrar el DataFrame original por esas fechas y ordenar
    df_repetidas = df_febrero[df_febrero['fecha'].isin(fechas_repetidas)].sort_values('fecha')
    display(df_repetidas)

Total de fechas con repeticiones: 28

Fechas repetidas y su frecuencia:
fecha
2026-02-20 07:30:00    2
2026-02-14 01:50:00    2
2026-02-23 07:10:00    2
2026-02-24 08:15:00    2
2026-02-26 23:55:00    2
2026-02-25 01:05:00    2
2026-02-01 09:50:00    2
2026-02-13 07:05:00    2
2026-02-04 23:10:00    2
2026-02-03 02:40:00    2
2026-02-05 04:30:00    2
2026-02-04 17:35:00    2
2026-02-12 03:05:00    2
2026-02-12 07:40:00    2
2026-02-26 16:05:00    2
2026-02-11 01:20:00    2
2026-02-17 06:45:00    2
2026-02-26 03:15:00    2
2026-02-01 07:55:00    2
2026-02-16 07:00:00    2
2026-02-02 03:45:00    2
2026-02-28 16:40:00    2
2026-02-22 08:50:00    2
2026-02-18 06:10:00    2
2026-02-15 01:55:00    2
2026-02-07 16:40:00    2
2026-02-27 03:20:00    2
2026-02-21 20:05:00    2
Name: count, dtype: int64

                   fecha  nivel
107  2026-02-01 07:55:00  6.525
108  2026-02-01 07:55:00  6.525
131  2026-02-01 09:50:00  6.521
132  2026-02-01 09:50:00  6.521
345  2026-02-02 03:45:00  6.525
346  2026-02-02 03:45:00  6.525
619  2026-02-03 02:40:00  6.491
620  2026-02-03 02:40:00  6.491
1038 2026-02-04 17:35:00  6.488
1039 2026-02-04 17:35:00  6.488
1101 2026-02-04 23:10:00  6.498
1102 2026-02-04 23:10:00  6.498
1166 2026-02-05 04:30:00  6.509
1165 2026-02-05 04:30:00  6.509
1393 2026-02-07 16:40:00  6.490
1394 2026-02-07 16:40:00  6.490
1476 2026-02-11 01:20:00  6.502
1477 2026-02-11 01:20:00  6.502
1681 2026-02-12 03:05:00  6.507
1682 2026-02-12 03:05:00  6.507
1734 2026-02-12 07:40:00  6.510
1735 2026-02-12 07:40:00  6.510
2012 2026-02-13 07:05:00  6.139
2013 2026-02-13 07:05:00  6.139
2233 2026-02-14 01:50:00  6.461
2234 2026-02-14 01:50:00  6.461
2519 2026-02-15 01:55:00  6.473
2518 2026-02-15 01:55:00  6.473
2816 2026-02-16 07:00:00  6.476
2817 2026-02-16 07:00:00  6.476
3099 2026-02-17 06:45:00  6.478
3100 2026-02-17 06:45:00  6.478
3376 2026-02-18 06:10:00  6.481
3377 2026-02-18 06:10:00  6.481
3870 2026-02-20 07:30:00  6.483
3871 2026-02-20 07:30:00  6.483
4273 2026-02-21 20:05:00  6.478
4274 2026-02-21 20:05:00  6.478
4425 2026-02-22 08:50:00  6.470
4426 2026-02-22 08:50:00  6.470
4691 2026-02-23 07:10:00  6.483
4690 2026-02-23 07:10:00  6.483
4987 2026-02-24 08:15:00  6.457
4988 2026-02-24 08:15:00  6.457
5188 2026-02-25 01:05:00  6.442
5189 2026-02-25 01:05:00  6.442
5501 2026-02-26 03:15:00  6.466
5502 2026-02-26 03:15:00  6.466
5653 2026-02-26 16:05:00  6.440
5654 2026-02-26 16:05:00  6.440
5746 2026-02-26 23:55:00  6.458
5747 2026-02-26 23:55:00  6.458
5787 2026-02-27 03:20:00  6.470
5788 2026-02-27 03:20:00  6.470
6231 2026-02-28 16:40:00  6.458
6232 2026-02-28 16:40:00  6.458

In [7]:
# =============================================
# ELIMINAR FILAS CON FECHA DUPLICADA (conservar la primera)
# =============================================

# Verificar cuántas filas tenemos antes
print(f"Filas antes de eliminar duplicados: {len(df_febrero)}")

# Identificar fechas repetidas (opcional, solo para diagnóstico)
duplicados_fecha = df_febrero.duplicated(subset=['fecha'], keep=False)
print(f"Filas con fecha duplicada (incluyendo primera aparición): {duplicados_fecha.sum()}")
if duplicados_fecha.sum() > 0:
    print("Ejemplo de fechas repetidas (primeras 5):")
    display(df_febrero[duplicados_fecha].sort_values('fecha').head(10))

# Eliminar duplicados basados en la columna 'fecha', conservando la primera ocurrencia
df_febrero = df_febrero.drop_duplicates(subset=['fecha'], keep='first')

# Verificar después
print(f"Filas después de eliminar duplicados: {len(df_febrero)}")

Filas antes de eliminar duplicados: 6304
Filas con fecha duplicada (incluyendo primera aparición): 56
Ejemplo de fechas repetidas (primeras 5):

                   fecha  nivel
107  2026-02-01 07:55:00  6.525
108  2026-02-01 07:55:00  6.525
131  2026-02-01 09:50:00  6.521
132  2026-02-01 09:50:00  6.521
345  2026-02-02 03:45:00  6.525
346  2026-02-02 03:45:00  6.525
619  2026-02-03 02:40:00  6.491
620  2026-02-03 02:40:00  6.491
1038 2026-02-04 17:35:00  6.488
1039 2026-02-04 17:35:00  6.488

Filas después de eliminar duplicados: 6276

In [8]:
#  Contar cuántos duplicados quedan (debe ser 0)
print("Número de filas con fecha duplicada:", df_febrero.duplicated(subset=['fecha']).sum())

Número de filas con fecha duplicada: 0

In [9]:
df_febrero['fecha'] = df_febrero['fecha'] + pd.Timedelta(hours=1) #adelanto de hora

In [10]:
df_febrero

                   fecha  nivel
0    2026-02-01 00:00:00  6.519
1    2026-02-01 00:05:00  6.518
2    2026-02-01 00:10:00  6.519
3    2026-02-01 00:15:00  6.518
4    2026-02-01 00:20:00  6.519
...                  ...    ...
6299 2026-02-28 23:30:00  6.457
6300 2026-02-28 23:35:00  6.458
6301 2026-02-28 23:40:00  6.459
6302 2026-02-28 23:50:00  6.460
6303 2026-02-28 23:55:00  6.461

[6276 rows x 2 columns]

In [11]:
# =============================================
# Crear índice regular de 5 minutos y reindexar
# =============================================

# Asegurar que la columna 'fecha' sea el índice
df_febrero = df_febrero.set_index('fecha').sort_index()

# Definir rango completo
start_time = df_febrero.index.min()
end_time = df_febrero.index.max()
time_index = pd.date_range(start=start_time, end=end_time, freq='5min')

# Reindexar: las marcas faltantes quedarán con NaN
df_regular = df_febrero.reindex(time_index)
df_regular.index.name = 'fecha'

# Verificar cuántos NaN se han introducido
print(f"Filas después de reindexar: {len(df_regular)}")
print(f"Valores nulos en 'nivel': {df_regular['nivel'].isna().sum()}")

Filas después de reindexar: 8064
Valores nulos en 'nivel': 1788

In [12]:
# Interpolar linealmente los valores nulos en la columna 'nivel'
df_regular['nivel'] = df_regular['nivel'].interpolate(method='linear')

# Verificar que ya no hay nulos
print("Valores nulos después de interpolar:", df_regular['nivel'].isna().sum())

Valores nulos después de interpolar: 0

In [13]:
# =============================================
# APLICAR  (7 - nivel)
#
# =============================================
df_regular['nivel'] = 7 - df_regular['nivel']

In [ ]:
# =============================================
# VERIFICAR FRECUENCIA UNIFORME (5 minutos)
# =============================================
diffs = df_regular.index.to_series().diff()
print("\nFrecuencia de las diferencias entre timestamps (debe ser 5 minutos):")
print(diffs.value_counts())

Frecuencia de las diferencias entre timestamps (debe ser 5 minutos):
fecha
0 days 00:05:00    8063
Name: count, dtype: int64

In [ ]:
# =============================================
# GRAFICAR INTERACTIVAMENTE CON PLOTLY
# =============================================
import plotly.express as px

fig = px.line(df_regular, x=df_regular.index, y='nivel',
              title='Nivel de agua (m) – Febrero 2026 (corregido +1h, interpolado)')
fig.update_layout(hovermode='x unified')
fig.show()

In [ ]:
import os
# Definir ruta en Drive
ruta_drive = '/content/drive/MyDrive/Colab Notebooks/IA/Mburicao/Datos_Febrero_2026'
os.makedirs(ruta_drive, exist_ok=True)

# 1. DataFrame de 5 minutos (ya debe existir df_regular)
df_regular['nivel'] = df_regular['nivel'].round(4)  # Asegura 4 decimales

# Guardar Excel 5min
archivo_5min = os.path.join(ruta_drive, 'Mburicao_febrero_2026_5min.xlsx')
df_regular.to_excel(archivo_5min)
print(f"Archivo de 5 min guardado en: {archivo_5min}")
# Guardar CSV 5min
archivo_5min_csv = os.path.join(ruta_drive, 'Mburicao_febrero_2026_5min.csv')
df_regular.to_csv(archivo_5min_csv, index=True)  # index=True incluye la fecha como primera columna
print(f"Archivo CSV de 5 min guardado en: {archivo_5min_csv}")

Archivo de 5 min guardado en: /content/drive/MyDrive/Colab Notebooks/IA/Mburicao/Datos_Febrero_2026/Mburicao_febrero_2026_5min.xlsx
Archivo CSV de 5 min guardado en: /content/drive/MyDrive/Colab Notebooks/IA/Mburicao/Datos_Febrero_2026/Mburicao_febrero_2026_5min.csv